[options]
admin_passwd = zgroup_local_master
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
without_demo = True
max_cron_threads = 0
list_db = True
http_interface = 0.0.0.0
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
